inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  DisabledByDefault: false

# Align `end` with the matching keyword or starting expression except for
# assignments, where it should be aligned with the LHS.
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/spec_helper.rb'
    - '**/**_spec.rb'
