before_install: gem install bundler
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
gemfile:
  - Gemfile
addons:
  postgresql: "9.4"
env:
  - PGUSER=postgres
before_script:
  - psql -c 'create database message_bus_test;' -U postgres
services:
  - redis-server
  - postgresql
